name: shipcube-backend
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - fastapi
      - uvicorn[standard]
      - python-multipart
      - pydantic
      - email-validator
      - beautifulsoup4
      - lxml
      - transformers
      - torch
      - sentence-transformers
      - spacy
      - imapclient
      - msal
      - requests
      - python-dateutil
      - faiss-cpu
      - pytest
